import type { Card, Flower } from "@/lib/types";

export const sampleCards: Card[] = [
  {
    id: "pressed-001",
    title: "春日拾光",
    priceTwd: 180,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 2,
    tags: {
      occasions: ["生日", "日常"],
      colors: ["粉", "黃", "奶油白"],
      flowers: ["繡球花", "卡斯比亞"],
      moods: ["溫柔", "祝福"],
    },
    blurb: "把春天留在掌心，適合送給想說謝謝的人。",
  },
  {
    id: "pressed-002",
    title: "晨光祝禱",
    priceTwd: 220,
    status: "custom_only",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "厚磅紙"],
    leadTimeDays: 7,
    tags: {
      occasions: ["畢業", "加油"],
      colors: ["粉", "綠"],
      flowers: ["星辰花", "香水合歡"],
      moods: ["鼓勵", "希望"],
    },
    blurb: "適合寫下一段短短的鼓勵，陪伴重要時刻。",
  },
  {
    id: "pressed-003",
    title: "靜靜想你",
    priceTwd: 260,
    status: "sold",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 0,
    tags: {
      occasions: ["紀念日", "思念"],
      colors: ["粉", "白"],
      flowers: ["細葉雪茄花", "夏堇"],
      moods: ["思念", "安定"],
    },
    blurb: "已售出；可委託相近風格的客製版本。",
  },
  {
    id: "pressed-004",
    title: "溫暖同行",
    priceTwd: 250,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 3,
    tags: {
      occasions: ["加油", "日常"],
      colors: ["黃", "橘"],
      flowers: ["台灣欒樹", "野毛蕨"],
      moods: ["鼓勵", "安定"],
    },
    blurb: "如暖陽般的色調，給予對方繼續前進的力量。",
  },
  {
    id: "pressed-005",
    title: "無盡優雅",
    priceTwd: 320,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "黑卡紙", "金箔"],
    leadTimeDays: 5,
    tags: {
      occasions: ["紀念日", "生日"],
      colors: ["黑", "紫"],
      flowers: ["黑王子蝴蝶蘭", "玫瑰"],
      moods: ["祝福", "思念"],
    },
    blurb: "神秘高貴的組合，適合送給特別的那個人。",
  },
  {
    id: "pressed-006",
    title: "自由之風",
    priceTwd: 190,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 2,
    tags: {
      occasions: ["畢業", "日常"],
      colors: ["藍", "白"],
      flowers: ["藍蝴蝶", "泡盛草"],
      moods: ["溫柔", "希望"],
    },
    blurb: "輕盈的姿態，宛如微風拂過，帶來自由的氣息。",
  },
  {
    id: "pressed-007",
    title: "永恆守候",
    priceTwd: 280,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 4,
    tags: {
      occasions: ["紀念日", "生日"],
      colors: ["紅", "粉"],
      flowers: ["玫瑰", "文竹", "滿天星"],
      moods: ["祝福", "安定"],
    },
    blurb: "經典的搭配，訴說著不變的情感與守護。",
  },
  {
    id: "pressed-008",
    title: "初夏生機",
    priceTwd: 210,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 2,
    tags: {
      occasions: ["加油", "日常"],
      colors: ["紅", "綠"],
      flowers: ["九重葛", "仙丹花"],
      moods: ["鼓勵", "溫柔"],
    },
    blurb: "充滿生命力的紅綠撞色，給予滿滿的能量。",
  },
  {
    id: "pressed-009",
    title: "純真年代",
    priceTwd: 170,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 1,
    tags: {
      occasions: ["生日", "日常"],
      colors: ["白", "粉"],
      flowers: ["白色櫻花", "小牽牛花"],
      moods: ["溫柔", "思念"],
    },
    blurb: "淡雅的配色，喚起最純粹美好的回憶。",
  },
  {
    id: "pressed-010",
    title: "勇敢前行",
    priceTwd: 230,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 3,
    tags: {
      occasions: ["畢業", "加油"],
      colors: ["黃", "紅"],
      flowers: ["金魚草", "鐵刀木"],
      moods: ["鼓勵", "希望"],
    },
    blurb: "獻給即將踏上新旅程的你，充滿力量與信心。",
  },
  {
    id: "pressed-011",
    title: "寧靜之森",
    priceTwd: 200,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 2,
    tags: {
      occasions: ["日常", "加油"],
      colors: ["綠", "棕"],
      flowers: ["美國肖楠", "葫蘆蘚", "構樹"],
      moods: ["安定", "溫柔"],
    },
    blurb: "帶有木質調的森林氣息，象徵繁榮與福氣。",
  },
  {
    id: "pressed-012",
    title: "秋日思念",
    priceTwd: 190,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 2,
    tags: {
      occasions: ["思念", "紀念日"],
      colors: ["紅", "棕"],
      flowers: ["落羽杉", "馬蘭"],
      moods: ["思念", "溫柔"],
    },
    blurb: "落羽杉的火羽滿載遍地的相思，訴說著深厚的情感。",
  },
  {
    id: "pressed-013",
    title: "熱情夏日",
    priceTwd: 210,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 3,
    tags: {
      occasions: ["生日", "加油"],
      colors: ["黃", "橘", "紅"],
      flowers: ["黃蝴蝶", "金英樹"],
      moods: ["鼓勵", "希望"],
    },
    blurb: "像陽光般熱情耀眼，帶來繁榮與快樂的生命力。",
  },
  {
    id: "pressed-014",
    title: "星夜呢喃",
    priceTwd: 260,
    status: "custom_only",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "深色卡紙"],
    leadTimeDays: 7,
    tags: {
      occasions: ["紀念日", "思念"],
      colors: ["紫", "黑"],
      flowers: ["紫葉酢漿草", "天使花"],
      moods: ["思念", "祝福"],
    },
    blurb: "在夜色中透出點點希望，象徵純真的記憶與愛。",
  },
  {
    id: "pressed-015",
    title: "守護天使",
    priceTwd: 220,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 2,
    tags: {
      occasions: ["生日", "日常"],
      colors: ["白", "粉"],
      flowers: ["蒜香藤", "米花"],
      moods: ["祝福", "溫柔"],
    },
    blurb: "互相思念的守護之心，帶著細膩溫暖的氣息。",
  },
  {
    id: "pressed-016",
    title: "繁花盛景",
    priceTwd: 350,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 15×20 cm",
    materials: ["壓花", "特種紙", "金箔"],
    leadTimeDays: 5,
    tags: {
      occasions: ["紀念日", "生日"],
      colors: ["紅", "粉", "白"],
      flowers: ["香水月季", "月季", "垂枝茉莉"],
      moods: ["祝福", "安定"],
    },
    blurb: "華麗盛開的經典之作，象徵長久與純潔的愛。",
  },
  {
    id: "pressed-017",
    title: "堅韌之光",
    priceTwd: 180,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 1,
    tags: {
      occasions: ["加油", "畢業"],
      colors: ["紫", "綠"],
      flowers: ["長穗木", "彩葉草"],
      moods: ["鼓勵", "安定"],
    },
    blurb: "無論面對何種挑戰，都能保持內心的平靜與堅韌。",
  },
  {
    id: "pressed-018",
    title: "微風鈴音",
    priceTwd: 210,
    status: "sold",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 0,
    tags: {
      occasions: ["日常", "生日"],
      colors: ["黃", "橘"],
      flowers: ["風鈴花", "金露花"],
      moods: ["祝福", "溫柔"],
    },
    blurb: "遠方傳來的祝福，如同風鈴般清脆悅耳。",
  },
  {
    id: "pressed-019",
    title: "青春印記",
    priceTwd: 190,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 2,
    tags: {
      occasions: ["畢業", "日常"],
      colors: ["紅", "粉"],
      flowers: ["紅櫻花", "兔仔菜"],
      moods: ["鼓勵", "溫柔"],
    },
    blurb: "刻畫青春活力的紅櫻，保留最坦率純真的時光。",
  },
  {
    id: "pressed-020",
    title: "女神之吻",
    priceTwd: 280,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 3,
    tags: {
      occasions: ["紀念日", "生日"],
      colors: ["紅", "粉", "白"],
      flowers: ["桃金孃", "針葉櫻桃"],
      moods: ["祝福", "希望"],
    },
    blurb: "愛與美之神的祝福，帶來無盡的幸福與活力。",
  },
  {
    id: "pressed-021",
    title: "南美風情",
    priceTwd: 200,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 2,
    tags: {
      occasions: ["日常", "生日"],
      colors: ["紅", "綠"],
      flowers: ["南美朱槿", "血喜花"],
      moods: ["溫柔", "鼓勵"],
    },
    blurb: "充滿才華與浪漫的生機，點燃生活中的熱情。",
  },
  {
    id: "pressed-022",
    title: "高潔靈魂",
    priceTwd: 240,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 2,
    tags: {
      occasions: ["加油", "紀念日"],
      colors: ["藍", "紫"],
      flowers: ["藍花木", "立鶴花"],
      moods: ["安定", "祝福"],
    },
    blurb: "純潔高貴的象徵，獻給擁有優雅品格的你。",
  },
  {
    id: "pressed-023",
    title: "懷舊時光",
    priceTwd: 190,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "牛皮紙"],
    leadTimeDays: 1,
    tags: {
      occasions: ["思念", "日常"],
      colors: ["紅", "橘"],
      flowers: ["新幾內亞鳳仙花", "射干"],
      moods: ["思念", "溫柔"],
    },
    blurb: "幸福即將到來，懷念那些曾經燦爛的日子。",
  },
  {
    id: "pressed-024",
    title: "珍貴純潔",
    priceTwd: 230,
    status: "available",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 3,
    tags: {
      occasions: ["紀念日", "生日"],
      colors: ["白", "紅"],
      flowers: ["龍吐珠", "野牡丹"],
      moods: ["祝福", "安定"],
    },
    blurb: "吉祥純潔的龍吐珠，搭配溫柔英勇的野牡丹。",
  },
  {
    id: "pressed-025",
    title: "晨露百花",
    priceTwd: 300,
    status: "custom_only",
    images: ["/demo/pressed-cards.png"],
    size: "約 10×15 cm",
    materials: ["壓花", "紙材"],
    leadTimeDays: 6,
    tags: {
      occasions: ["畢業", "生日"],
      colors: ["粉", "藍", "黃"],
      flowers: ["繡球花", "小牽牛花", "夏堇"],
      moods: ["希望", "溫柔"],
    },
    blurb: "集結各式小花，宛如清晨沾滿露水的花園，充滿生機。",
  }
];

export const sampleFlowers: Flower[] = [
  {
    id: "hydrangea",
    name: "繡球花",
    meanings: ["希望", "美滿", "團圓", "真摯情感", "包容", "專一的愛", "愛"],
    story:
      "繡球花（八仙花／紫陽花）的花語包含希望、美滿、團圓、真摯情感、包容、專一的愛等，但其具體含義常因顏色而異：白色象徵希望、包容；藍色代表浪漫美滿，也常被解讀為道歉之意；粉紅色代表表達心的感情；紫色象徵團圓與親密關係；綠色代表專一、執著的愛。",
    relatedTags: ["希望", "團圓", "愛", "美滿"],
  },
  {
    id: "little-morning-glory",
    name: "小牽牛花",
    meanings: ["柔和心", "愛情", "團結", "連繫", "希望", "美好未來", "神秘", "高貴", "純潔"],
    story:
      "小牽牛花的傳統花語常被整理為與大自然同在的柔和心、愛情、團結、與你連繫在一起，也象徵希望與美好未來；常見延伸：粉色代表愛與情感，白色象徵純潔，紫色代表神秘與高貴。",
    relatedTags: ["希望", "愛情", "團結"],
  },
  {
    id: "calliandra-brevipes",
    name: "香水合歡",
    meanings: ["永恆恩愛", "兩相對", "溫柔", "愛情", "團結", "連結"],
    story:
      "香水合歡（學名 Calliandra brevipes），又稱細葉粉撲花／粉撲樹，花語常整理為「永恆恩愛」、「兩相對」，象徵忠貞的愛情、美滿的家庭與深厚情誼；花朵細長飄逸如粉撲，因此得名。",
    relatedTags: ["愛情", "永恆", "家庭"],
  },
  {
    id: "statice-limonium-sinuatum",
    name: "星辰花",
    meanings: ["永恆的愛", "不變的心", "持久不變", "深厚情誼"],
    story:
      "星辰花（Limonium sinuatum，Statice；常見俗稱不凋花）常被解讀象徵永恆的愛、不變的心、持久不變與深厚情誼；常見說法源於其乾燥後仍能長時間保持色澤，如同永恆的記憶。",
    relatedTags: ["永恆", "友情", "愛"],
  },
  {
    id: "caspia",
    name: "卡斯比亞",
    meanings: ["真誠喜悅"],
    story:
      "卡斯比亞（Caspia）花語常見為「真誠喜悅」，也常被稱作「情人草」；淡雅紫色、姿態輕盈，常用於花束搭配，乾燥後也能長久保存。",
    relatedTags: ["喜悅", "真誠"],
  },
  {
    id: "china-rose",
    name: "月季",
    meanings: ["希望", "美滿", "光榮", "幸福"],
    story:
      "月季（China rose / monthly rose）的總體花語常見為希望、美滿、光榮，也象徵不屈不撓與對未來的期盼；顏色延伸常見：紅色代表熱烈的愛，粉色象徵溫柔與優雅，白色寓意純潔與尊敬。",
    relatedTags: ["希望", "幸福"],
  },
  {
    id: "rose",
    name: "玫瑰",
    meanings: ["愛情", "美麗"],
    story:
      "玫瑰的花語主要圍繞愛情與美麗；常見延伸：紅玫瑰代表熱情與熱戀，白玫瑰象徵純潔與尊敬，粉玫瑰傳達初戀與傾慕，藍玫瑰象徵奇蹟與夢想；朵數也常被賦予含義，例如 1 朵代表一見鍾情，99 朵寓意長相廝守。",
    relatedTags: ["愛情"],
  },
  {
    id: "bougainvillea",
    name: "九重葛",
    meanings: ["熱情", "繁榮", "生命力", "堅韌"],
    story:
      "九重葛（Bougainvillea，亦稱三角梅）常見花語為熱情，也包含繁榮、生命力與堅韌；常見解釋與其鮮豔苞片、層層疊疊花序與長久觀賞期等特性相連結。",
    relatedTags: ["熱情", "繁榮"],
  },
  {
    id: "ixora-chinensis",
    name: "仙丹花",
    meanings: ["熱情", "團結", "獲得新生"],
    story:
      "仙丹花（Ixora chinensis）的花語主要為熱情、團結、獲得新生；也因花朵密集簇生，在傳統文化中常用來祝福「早生貴子」，亦被延伸為榮譽的象徵。",
    relatedTags: ["熱情", "團結"],
  },
  {
    id: "bleeding-heart-vine",
    name: "龍吐珠",
    meanings: ["珍貴純潔", "內心熱誠", "幸福吉祥"],
    story:
      "龍吐珠（常見標示 Clerodendrum thomsoniae）花語常整理為珍貴純潔、內心熱誠與幸福吉祥；也常被延伸為吉祥裝飾之意，並被解讀象徵智慧與財富。",
    relatedTags: ["幸福", "吉祥"],
  },
  {
    id: "alternanthera",
    name: "彩葉草",
    meanings: ["穩定", "耐心"],
    story:
      "彩葉草（Alternanthera）常見花語為穩定與耐心，亦常被延伸為堅韌不拔、寧靜平和與繁榮穩定的象徵。",
    relatedTags: ["穩定"],
  },
  {
    id: "christella-dentata",
    name: "野毛蕨",
    meanings: ["富貴吉祥", "生生不息"],
    story:
      "野毛蕨（Christella dentata，亦稱小毛蕨）常被理解為吉祥與生生不息的寓意；蕨類亦常被視為聚集財富與生長力量的象徵。",
    relatedTags: ["吉祥"],
  },
  {
    id: "cuphea-hyssopifolia",
    name: "細葉雪茄花",
    meanings: ["思念", "愛情", "堅持", "自由", "持久", "力量"],
    story:
      "細葉雪茄花（Cuphea hyssopifolia）的花語常見為思念與愛情，也被延伸為堅持與自由；因能在相對惡劣環境中茁壯成長，也象徵持久與力量。",
    relatedTags: ["思念", "愛情"],
  },
  {
    id: "aster-indicus",
    name: "馬蘭",
    meanings: ["幸福", "喜悅", "永恆的愛", "思念"],
    story:
      "馬蘭（Aster indicus）的花語常被整理為幸福、喜悅、永恆的愛與思念遠方的人，也常被延伸為追憶、勤勞與財富的象徵。",
    relatedTags: ["幸福", "思念"],
  },
  {
    id: "torenia-fournieri",
    name: "夏堇",
    meanings: ["請想念我", "思念但迷茫", "青春", "純真的喜悅"],
    story:
      "夏堇（Torenia fournieri）的花語常見為「請想念我」、「思念但感到迷茫」，也常被延伸為青春與純真的喜悅，象徵生命的輝煌與堅韌。",
    relatedTags: ["思念", "青春"],
  },
  {
    id: "ixeris-chinensis",
    name: "兔仔菜",
    meanings: ["溫柔", "純真"],
    story:
      "兔仔菜（Ixeris chinensis）在原始筆記中以「溫柔與純真」作為花語整理。",
    relatedTags: ["溫柔"],
  },
  {
    id: "blue-butterfly-bush",
    name: "藍蝴蝶",
    meanings: ["自由", "變化"],
    story: "藍蝴蝶（Blue Butterfly Bush）的花語代表自由與變化。",
    relatedTags: ["自由"],
  },
  {
    id: "snapdragon",
    name: "金魚草",
    meanings: ["清純的心", "力量", "勇氣"],
    story:
      "金魚草（Snapdragon）的花語常見為清純的心、力量與勇氣，也常被延伸寓意繁榮昌盛；其細節含義會因文化背景與花色而有所差異。",
    relatedTags: ["勇氣"],
  },
  {
    id: "tibouchina",
    name: "野牡丹",
    meanings: ["溫柔與耐心", "英勇"],
    story:
      "野牡丹在原始內容中同時出現兩種說法：其一花語代表溫柔與耐心；其二提到花語為英勇，並附上一段紀念事件的說法（原文保留）。",
    relatedTags: ["耐心"],
  },
  {
    id: "blackberry-lily",
    name: "射干",
    meanings: ["誠實", "幸福逐漸到來"],
    story:
      "射干（Blackberry lily）的花語為誠實、幸福逐漸到來；原始內容另提及「觀音蘭（射干菖蒲）」的延伸花語描述（熱情活力、好消息、快樂回憶）。",
    relatedTags: ["幸福"],
  },
  {
    id: "rosa-odorata",
    name: "香水月季",
    meanings: ["熱戀", "忠誠", "美好的未來", "友誼", "尊重"],
    story:
      "香水月季（Rosa odorata）的花語常整理為熱戀、忠誠與美好的未來，也延伸為友誼與尊重；原始內容同時提到月季在中國文化中亦常被解讀象徵長壽與不屈不撓。",
    relatedTags: ["愛情", "忠誠"],
  },
  {
    id: "stachytarpheta-urticaefolia",
    name: "長穗木",
    meanings: ["內心平靜", "堅韌", "毅力", "耐心", "堅持"],
    story:
      "長穗木（Stachytarpheta urticaefolia，紫花長穗木）在原始內容中的花語重點為：面對外界壓力與衝突時，在困境中尋找內心平靜，並保持堅韌與毅力。",
    relatedTags: ["平靜", "堅韌"],
  },
  {
    id: "golden-dewdrop",
    name: "金露花",
    meanings: ["尊敬", "祝福"],
    story:
      "金露花（Golden Dewdrop / Duranta erecta，假連翹）的花語為尊敬與祝福；也常被延伸象徵好運、吉祥、財富、迎賓與守護家園的安心感。",
    relatedTags: ["祝福"],
  },
  {
    id: "callianthe-picta",
    name: "風鈴花",
    meanings: ["感謝與長久", "忠誠", "來自遠方的祝福", "堅韌不拔", "溫柔與和諧", "嫉妒"],
    story:
      "風鈴花（Callianthe picta）的正面花語常見為感謝與長久，也延伸為忠誠、來自遠方的祝福、堅韌不拔、溫柔與和諧；負面花語：嫉妒。",
    relatedTags: ["感謝", "祝福"],
  },
  {
    id: "acerola",
    name: "針葉櫻桃",
    meanings: ["健康", "豐盛", "活力", "青春", "甜美", "獨特的愛", "珍貴的愛"],
    story:
      "針葉櫻桃（Acerola cherry）花語常與其果實富含維生素 C 的特性連結，被解讀象徵健康、豐盛、活力、青春與甜美；也被延伸為獨特、珍貴的愛。",
    relatedTags: ["健康", "活力"],
  },
  {
    id: "rhodomyrtus",
    name: "桃金孃",
    meanings: ["女神", "美麗", "幸福", "愛情"],
    story:
      "桃金孃（Rhodomyrtus，桃金娘）代表性花語為「女神」，象徵美麗、幸福與對土地的呵護；原始內容亦提到其在西方文化中被視為愛與美之女神的聖樹，代表愛情。",
    relatedTags: ["幸福", "愛情"],
  },
  {
    id: "caesalpinia-pulcherrima",
    name: "黃蝴蝶",
    meanings: ["快樂活潑", "持續的成長", "繁榮與振興"],
    story:
      "黃蝴蝶（Caesalpinia pulcherrima）的花語常整理為快樂活潑、持續的成長、繁榮與振興；原始內容亦提到其與夏季盛開、生命力與繁榮能量的聯想。",
    relatedTags: ["快樂", "繁榮"],
  },
  {
    id: "galphimia-gracilis",
    name: "金英樹",
    meanings: ["全心全意把愛奉獻給你", "誠實的愛", "真愛", "喜悅", "幸福", "新起點", "希望", "厚道", "堅持後的綻放"],
    story:
      "金英樹（Galphimia gracilis，金英花）的花語包含全心全意把愛奉獻給你、誠實的愛、真愛，以及喜悅、幸福、新起點、希望和厚道；也象徵「堅持後的綻放」。",
    relatedTags: ["希望", "幸福", "愛"],
  },
  {
    id: "asparagus-setaceus",
    name: "文竹",
    meanings: ["永恆", "純潔", "不變的愛情", "友情", "家庭幸福美滿", "長久的友誼"],
    story:
      "文竹（Asparagus setaceus）的花語主要是永恆，象徵純潔、不變的愛情與友情，也代表家庭的幸福美滿與長久的友誼；常被用於婚禮配材，寄託對愛情地久天長的祝福。",
    relatedTags: ["永恆", "祝福"],
  },
  {
    id: "malvaviscus",
    name: "南美朱槿",
    meanings: ["才華橫溢", "浪漫迷人", "溫柔", "羞澀", "熱情", "生機"],
    story:
      "南美朱槿（Malvaviscus）的花語是才華橫溢、浪漫迷人，象徵含苞待放的溫柔與羞澀，也寓意熱情與生機。",
    relatedTags: ["浪漫", "熱情"],
  },
  {
    id: "mussaenda",
    name: "血喜花",
    meanings: ["成長", "繁榮", "活力", "更新", "堅韌", "熱情"],
    story:
      "血喜花（Mussaenda）的花語在原始內容中以成長、繁榮、活力、更新為主，也常被延伸連結生命力、堅韌與熱情，並被解讀象徵祝福。",
    relatedTags: ["成長", "活力"],
  },
  {
    id: "calocedrus",
    name: "美國肖楠",
    meanings: ["成長", "繁榮", "活力", "更新", "新的開始"],
    story:
      "美國肖楠（Calocedrus；原始內容註記通常指台灣肖楠木）的花語多與風水象徵連結，代表成長、繁榮、活力與更新，也寓意新的開始；原始內容亦提到其香氣與放鬆舒壓、提升專注的聯想。",
    relatedTags: ["成長", "新開始"],
  },
  {
    id: "indigofera-spicata",
    name: "藍花木",
    meanings: ["純潔", "高貴"],
    story:
      "藍花木（Indigofera spicata）的花語為純潔與高貴；原始內容亦補充其在西方常被用於婚禮象徵純潔與愛情，在東方被解讀為涵養與高潔。",
    relatedTags: ["純潔"],
  },
  {
    id: "paper-mulberry",
    name: "構樹",
    meanings: ["財富", "生計", "富足"],
    story:
      "構樹（Broussonetia；Paper mulberry）的花語整理為財富、生計與富足。",
    relatedTags: ["財富"],
  },
  {
    id: "oxalis-triangularis",
    name: "紫葉酢漿草",
    meanings: ["幸福", "愛情與忠誠", "快樂與愛"],
    story:
      "紫葉酢漿草（Oxalis triangularis）的花語常整理為幸福、愛情與忠誠，以及快樂與愛。",
    relatedTags: ["幸福", "愛"],
  },
  {
    id: "funaria",
    name: "葫蘆蘚",
    meanings: ["吉祥", "福氣", "財富", "純潔"],
    story:
      "葫蘆蘚（Funaria）的含義多樣，最主要與「福祿」諧音，代表吉祥、福氣與財富；原始內容亦提到在某些文化中被賦予純潔的花語。",
    relatedTags: ["吉祥", "財富"],
  },
  {
    id: "sakura-white",
    name: "白色櫻花",
    meanings: ["純潔", "高尚", "淡泊", "除你之外別無他愛"],
    story:
      "白色櫻花的花語核心是「純潔」、「高尚」、「淡泊」與「除你之外，別無他愛」。也常被解讀象徵愛情與希望。",
    relatedTags: ["純潔", "愛"],
  },
  {
    id: "sakura-red",
    name: "紅櫻花",
    meanings: ["熱烈", "坦率", "純潔", "高雅", "美麗的心靈", "青春", "活力"],
    story:
      "紅櫻花（特別是山櫻花）的花語常被解讀象徵熱烈、坦率、純潔、高雅與美麗的心靈，也被視為青春與活力的象徵。",
    relatedTags: ["青春"],
  },
  {
    id: "clerodendrum-laevifolium",
    name: "垂枝茉莉",
    meanings: ["純潔", "優雅", "友誼", "忠貞不渝的愛"],
    story:
      "垂枝茉莉（Clerodendrum laevifolium，又稱垂絲茉莉、白玉蝴蝶）的花語為純潔、優雅、友誼、忠貞不渝的愛。",
    relatedTags: ["友情", "愛"],
  },
  {
    id: "astilbe-japonica",
    name: "泡盛草",
    meanings: ["清澈的愛", "戀愛的來臨", "自由"],
    story:
      "泡盛草（Astilbe japonica / Astilbe）的花語常見為「我願清澈的愛著你」、「戀愛的來臨」或「自由」；因花形夢幻，也常用作婚禮捧花象徵甜蜜純粹的愛情。",
    relatedTags: ["愛情", "自由"],
  },
  {
    id: "angelonia-salicariifolia",
    name: "天使花",
    meanings: ["天使的純真", "美好的記憶", "純潔", "希望", "新開始"],
    story:
      "天使花（Angelonia salicariifolia）傳統花語常整理為天使的純真與美好的記憶，也代表純潔、希望、新開始等延伸含義。",
    relatedTags: ["希望", "新開始"],
  },
  {
    id: "thunbergia-erecta",
    name: "立鶴花",
    meanings: ["忠貞", "節操", "高貴", "優雅"],
    story:
      "立鶴花（Thunbergia erecta）的花語主要為忠貞、節操，也延伸出高貴與優雅，常用來表達堅定信念與品格。",
    relatedTags: ["忠誠"],
  },
  {
    id: "cassia-siem",
    name: "鐵刀木",
    meanings: ["力量與信心", "堅韌", "勇氣"],
    story:
      "鐵刀木的花語是力量與信心，代表面對困難時的堅韌不拔與勇氣，也象徵堅定信念與克服挑戰的精神。",
    relatedTags: ["力量", "勇氣"],
  },
  {
    id: "rice-flower",
    name: "米花",
    meanings: ["喜悅", "知足常樂", "暗戀", "告白", "長壽", "幸福", "著迷", "守護"],
    story:
      "「米花／米粒（Rice flower）」在原始內容中指出可能指涉多種花卉（如米香花／小米花、米迦勒菊），花語彙整包含喜悅、知足常樂、暗戀、告白、長壽、幸福與著迷；另有一支系統整理為統率力、純潔與守護。",
    relatedTags: ["幸福", "告白"],
  },
  {
    id: "impatiens-hawkeri",
    name: "新幾內亞鳳仙花",
    meanings: ["懷念過去", "活力", "熱情", "友誼"],
    story:
      "新幾內亞鳳仙花（Impatiens hawkeri）的花語是懷念過去，也象徵活力、熱情與友誼；常被用來表達對過往美好時光的懷念。",
    relatedTags: ["友誼", "懷念"],
  },
  {
    id: "mansoa-alliacea",
    name: "蒜香藤",
    meanings: ["互相思念", "勇氣", "守護"],
    story:
      "蒜香藤（Mansoa alliacea）的花語是互相思念，也代表勇氣與守護；原始內容將其與獨特香氣及象徵力量的聯想連結。",
    relatedTags: ["思念", "守護"],
  },
  {
    id: "black-prince-moth-orchid",
    name: "黑王子蝴蝶蘭",
    meanings: ["高雅", "美好", "幸福到來", "我愛你"],
    story:
      "黑王子蝴蝶蘭的花語為高雅、美好、幸福到來、我愛你；蝴蝶蘭整體也常被解讀寓意吉祥、喜慶與純潔的愛與友情，「黑王子」品種更增添神秘高貴的氣質。",
    relatedTags: ["幸福", "愛"],
  },
  {
    id: "taiwan-golden-rain-tree",
    name: "台灣欒樹",
    meanings: ["熱情", "開朗", "朝氣", "自由", "獨立", "溫暖陪伴"],
    story:
      "台灣欒樹（Taiwan golden rain tree）的花語主要為熱情、開朗與朝氣；原始內容也補充其被賦予自由、獨立，以及親情的呼喚和溫暖陪伴等含義。",
    relatedTags: ["熱情"],
  },
  {
    id: "bald-cypress",
    name: "落羽杉",
    meanings: ["火羽般的想念", "遍地的相思", "空靈", "重生"],
    story:
      "落羽杉（Bald Cypress，亦稱落羽松）的花語在原始內容中整理為「火羽般的想念、遍地的相思」與「空靈」，也被延伸解讀寓意重生。",
    relatedTags: ["思念"],
  },
];

